name: Daily Netlify Build

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at midnight UTC

jobs:
  trigger-netlify-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/677ffb84c2a842dfb7e8329d
